name: fibromyalgia_hospital
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_svg:
  flutter_launcher_icons:
  otp_text_field:
  iconsax:
  flutter_bloc:
  persistent_bottom_nav_bar:
  flutter_slidable:
  flutter_rating_bar:
  table_calendar:
  shared_preferences:
  get_it:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:


flutter:
  uses-material-design: true

  assets:
     - assets/images/


  fonts:
     - family: Rubik
       fonts:
         - asset: assets/fonts/Rubik-VariableFont_wght.ttf
         - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
           style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
