name: fibromyalgia_hospital
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  otp_text_field: ^1.1.3
  iconsax: ^0.0.8
  flutter_bloc: ^8.1.4
  persistent_bottom_nav_bar: ^5.0.2
  flutter_slidable: ^3.0.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.0
  shared_preferences:
  get_it:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/ahella/



  fonts:
     - family: Rubik
       fonts:
         - asset: assets/fonts/Rubik-VariableFont_wght.ttf
         - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
           style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
